### ISSUE TITLE
app_assemply configuration option should be mandatory

### ISSUE THREAD

**Issue by KarolStosik** [net-daemon/homeassistant-addon#61]
Other add-ons won't start unless some configuration values are provided. It will be helpful, to have the same feature for `app_assembly`. Below is a screen from Samba started without set password:

![obraz](https://github.com/net-daemon/homeassistant-addon/assets/26736701/5463545a-7646-4039-b347-981ce5527b74)

**Comment by helto4real** [comment]
app assembly is not mandatory. NetDaemon can be run with source only where ND will compile it. Called source delploy option that are some what limited that you cannot use external nuget packages
